#!/bin/bash

# if no file was provided
if [ "$#" -eq 0 ]; then
    echo "No file was provided"
    exit 1
fi

if [[ "$1" == "-help" ]]; then
    echo "Usage: dewiki <file to \"dewikize\">"
    exit 1
fi

# if the file/path does not exist
file="$*"
if [ ! -f "$file" ]; then
    echo "File does not exist: $file"
    exit 1
fi

# removes all [] from the text
sed -E -i 's/\[[0-9]+\]//g' "$file"
