#!/bin/bash
# author Christian Bargraser

# appends aliases to .bashrc
cat ./myUtil/myAliases.txt >> ~/.bashrc
rm ./myUtil/myAliases.txt
# deletes installer and readme
rm ./myUtil/installMyUtil
rm ./myUtil/README.md
# c programs
gcc -o dualdisp dualdislp.c
rm dualdisp.c
# gives everyone execute access
chmod +x ./myUtil/*
# moves scripts to /usr/local/bin
sudo mv ./myUtil/* /usr/local/bin
# deletes the cloned repository
rm -rf ./myUtil
